name: fyt_lyf_app
description: Fitness app with cinematic splash screen
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1   # Roboto (and many others) come from here
  numberpicker: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/welcome_bg.png
    - assets/images/female.png
    - assets/images/male.png